#!/usr/bin/env bash

export PATH="$PWD/setup:$PATH"

# ---------------------------------- Cleanup --------------------------------- #

log info "Cleaning up..."

for app in \
    "Finder" \
    "Safari"; do
    killall "${app}" &>/dev/null
done