#!/bin/bash
# shellcheck disable=SC1090

source "$DOTFILES_HOME/zsh/config/functions.zsh"
source "$DOTFILES_HOME/zsh/.zshenv"

STAGED_JS_AND_JSON=$(git diff --cached --name-only --diff-filter=ACMR "*.js" "*.jsx" "*.json" | sed 's| |\\ |g')
[ -z "$STAGED_JS_AND_JSON" ] && exit 0

if [[ -n "${STAGED_JS_AND_JSON}" ]]; then
    set -o errexit

    # Prettify everything
    echo "$STAGED_JS_AND_JSON" | xargs prettier --write

    # Add them back to staging so that the changes get committed
    echo "$STAGED_JS_AND_JSON" | xargs git add

    set +o errexit
fi
