#!/bin/bash
# shellcheck disable=SC1090

source "$DOTFILES_HOME/zsh/config/functions.zsh"
source "$DOTFILE_HOME/zsh/.zshenv"
source "$DOTFILE_HOME/zsh/.zshrc"

STAGED_JS_AND_JSON=$(git diff --cached --name-only | grep -iE "\.(js|json)$")

if [[ -n "${STAGED_JS_AND_JSON}" ]]; then
    set -o errexit

    for FILE in ${STAGED_JS_AND_JSON}; do
        prettier --write "$FILE"
    done

    set +o errexit
fi

HOMEBREW_NO_AUTO_UPDATE=1 backup-now
