# Setting PATHs
export GDRIVE="$HOME/Google Drive"
export LOCAL_BIN=/usr/local/bin
export ZSH=$HOME/.dotfiles/oh-my-zsh
export VSCODE="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export SSH_KEY_PATH=~/.ssh/rsa_id
export SCALA_HOME=/usr/local/share/scala
export GOPATH=$GDRIVE/Developer/GoWorkspace
export EMACSPATHVAR=$GDRIVE/Developer/_config/emacs
export NODEMODULEPATH=/usr/local/lib/node_modules
export PYTHON2_PKGS=/Library/Frameworks/Python.framework/Versions/2.7/bin
export PYTHON3_PKGS=/Library/Frameworks/Python.framework/Versions/3.7/bin
export PERLBREW=$HOME/perl5/perlbrew/bin
export RUST=$HOME/.cargo/bin
export MYSQL=/usr/local/mysql-8.0.11-macos10.13-x86_64/bin/
export TERM="xterm-256color"
export EDITOR='code'
export BAT_THEME="TwoDark"
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
export PATH="$PYTHON2_PKGS:$PYTHON3_PKGS:$NODEMODULEPATH:$GOPATH/bin:$EMACSPATHVAR:$HOME/bin:$LOCAL_BIN:$PERLBREW:$GOPATH/bin:$SCALA_HOME/bin:$MYSQL:$RUST:$VSCODE:$PATH"
