# Setting PATHs
export GDRIVE="$HOME/Google Drive"
export LOCAL_BIN=/usr/local/bin
export KEKA=/Applications/Keka.app/Contents/MacOS
export ZSH=$HOME/.dotfiles/oh-my-zsh
export MY_ZSH_SCRIPTS=$HOME/.zsh/scripts
export MY_ZSH_SECRETS=$HOME/.zshsecrets
export VSCODE="/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
export SSH_KEY_PATH=~/.ssh/rsa_id
export SCALA_HOME=/usr/local/share/scala
export GOPATH=$GDRIVE/Developer/GoWorkspace
export EMACSPATHVAR=$GDRIVE/Developer/_config/emacs
export NODEMODULEPATH=/usr/local/lib/node_modules
export PERLBREW=$HOME/perl5/perlbrew/bin
export RUST=$HOME/.cargo/bin
export MYSQL=/usr/local/mysql-8.0.11-macos10.13-x86_64/bin/
export TERM="xterm-256color"
export EDITOR='code'
export BAT_THEME="TwoDark"
export LDFLAGS="-L/usr/local/opt/libffi/lib"
export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"
export PYTHON2_PKGS="/usr/local/lib/python2.7/site-packages/"
export PATH="$KEKA:$MY_ZSH_SECRETS:$MY_ZSH_SCRIPTS:$PYTHON2_PKGS:$NODEMODULEPATH:$GOPATH/bin:$EMACSPATHVAR:$HOME/bin:$LOCAL_BIN:$PERLBREW:$GOPATH/bin:$SCALA_HOME/bin:$MYSQL:$RUST:$VSCODE:$PATH"
