# Kubectl/Kubectx/Kubens Aliases

## Mine
alias kx="kubectx"
alias kns="kubens"
alias kgen='kubectl get endpoints'
alias kgenns='kubectl get endpoints --namespace'
alias ked='kubectl edit'
alias keden='kubectl edit endpoints'
alias kedenns='kubectl edit endpoints --namespace'
alias kc='kubectl config'
alias kcv='kubectl config view'
alias kcvmin='kubectl config view --minify'
alias kcvminraw='kubectl config view --minify --raw'

## From github.com/ahmetb/kubectl-aliases
alias k='kubectl'
alias ka='kubectl apply --recursive -f'
alias kak='kubectl apply -k'
alias kk='kubectl kustomize'
alias kex='kubectl exec -i -t'
alias klo='kubectl logs -f'
alias klop='kubectl logs -f -p'
alias kp='kubectl proxy'
alias kpf='kubectl port-forward'
alias kg='kubectl get'
alias kd='kubectl describe'
alias krm='kubectl delete'
alias krun='kubectl run --rm --restart=Never --image-pull-policy=IfNotPresent -i -t'
alias kgpo='kubectl get pods'
alias kdpo='kubectl describe pods'
alias krmpo='kubectl delete pods'
alias kgdep='kubectl get deployment'
alias kddep='kubectl describe deployment'
alias krmdep='kubectl delete deployment'
alias kgsvc='kubectl get service'
alias kdsvc='kubectl describe service'
alias krmsvc='kubectl delete service'
alias kging='kubectl get ingress'
alias kding='kubectl describe ingress'
alias krming='kubectl delete ingress'
alias kgcm='kubectl get configmap'
alias kdcm='kubectl describe configmap'
alias krmcm='kubectl delete configmap'
alias kgsec='kubectl get secret'
alias kdsec='kubectl describe secret'
alias krmsec='kubectl delete secret'
alias kgno='kubectl get nodes'
alias kdno='kubectl describe nodes'
alias kgns='kubectl get namespaces'
alias kdns='kubectl describe namespaces'
alias krmns='kubectl delete namespaces'
alias kgoyaml='kubectl get -o=yaml'
alias kgpooyaml='kubectl get pods -o=yaml'
alias kgdepoyaml='kubectl get deployment -o=yaml'
alias kgsvcoyaml='kubectl get service -o=yaml'
alias kgingoyaml='kubectl get ingress -o=yaml'
alias kgcmoyaml='kubectl get configmap -o=yaml'
alias kgsecoyaml='kubectl get secret -o=yaml'
alias kgnooyaml='kubectl get nodes -o=yaml'
alias kgnsoyaml='kubectl get namespaces -o=yaml'
alias kgowide='kubectl get -o=wide'
alias kgpoowide='kubectl get pods -o=wide'
alias kgdepowide='kubectl get deployment -o=wide'
alias kgsvcowide='kubectl get service -o=wide'
alias kgingowide='kubectl get ingress -o=wide'
alias kgcmowide='kubectl get configmap -o=wide'
alias kgsecowide='kubectl get secret -o=wide'
alias kgnoowide='kubectl get nodes -o=wide'
alias kgnsowide='kubectl get namespaces -o=wide'
alias kgojson='kubectl get -o=json'
alias kgpoojson='kubectl get pods -o=json'
alias kgdepojson='kubectl get deployment -o=json'
alias kgsvcojson='kubectl get service -o=json'
alias kgingojson='kubectl get ingress -o=json'
alias kgcmojson='kubectl get configmap -o=json'
alias kgsecojson='kubectl get secret -o=json'
alias kgnoojson='kubectl get nodes -o=json'
alias kgnsojson='kubectl get namespaces -o=json'
alias kgall='kubectl get --all-namespaces'
alias kdall='kubectl describe --all-namespaces'
alias kgpoall='kubectl get pods --all-namespaces'
alias kdpoall='kubectl describe pods --all-namespaces'
alias kgdepall='kubectl get deployment --all-namespaces'
alias kddepall='kubectl describe deployment --all-namespaces'
alias kgsvcall='kubectl get service --all-namespaces'
alias kdsvcall='kubectl describe service --all-namespaces'
alias kgingall='kubectl get ingress --all-namespaces'
alias kdingall='kubectl describe ingress --all-namespaces'
alias kgcmall='kubectl get configmap --all-namespaces'
alias kdcmall='kubectl describe configmap --all-namespaces'
alias kgsecall='kubectl get secret --all-namespaces'
alias kdsecall='kubectl describe secret --all-namespaces'
alias kgnsall='kubectl get namespaces --all-namespaces'
alias kdnsall='kubectl describe namespaces --all-namespaces'
alias kgsl='kubectl get --show-labels'
alias kgposl='kubectl get pods --show-labels'
alias kgdepsl='kubectl get deployment --show-labels'
alias krmall='kubectl delete --all'
alias krmpoall='kubectl delete pods --all'
alias krmdepall='kubectl delete deployment --all'
alias krmsvcall='kubectl delete service --all'
alias krmingall='kubectl delete ingress --all'
alias krmcmall='kubectl delete configmap --all'
alias krmsecall='kubectl delete secret --all'
alias krmnsall='kubectl delete namespaces --all'
alias kgw='kubectl get --watch'
alias kgpow='kubectl get pods --watch'
alias kgdepw='kubectl get deployment --watch'
alias kgsvcw='kubectl get service --watch'
alias kgingw='kubectl get ingress --watch'
alias kgcmw='kubectl get configmap --watch'
alias kgsecw='kubectl get secret --watch'
alias kgnow='kubectl get nodes --watch'
alias kgnsw='kubectl get namespaces --watch'
alias kgoyamlall='kubectl get -o=yaml --all-namespaces'
alias kgpooyamlall='kubectl get pods -o=yaml --all-namespaces'
alias kgdepoyamlall='kubectl get deployment -o=yaml --all-namespaces'
alias kgsvcoyamlall='kubectl get service -o=yaml --all-namespaces'
alias kgingoyamlall='kubectl get ingress -o=yaml --all-namespaces'
alias kgcmoyamlall='kubectl get configmap -o=yaml --all-namespaces'
alias kgsecoyamlall='kubectl get secret -o=yaml --all-namespaces'
alias kgnsoyamlall='kubectl get namespaces -o=yaml --all-namespaces'
alias kgalloyaml='kubectl get --all-namespaces -o=yaml'
alias kgpoalloyaml='kubectl get pods --all-namespaces -o=yaml'
alias kgdepalloyaml='kubectl get deployment --all-namespaces -o=yaml'
alias kgsvcalloyaml='kubectl get service --all-namespaces -o=yaml'
alias kgingalloyaml='kubectl get ingress --all-namespaces -o=yaml'
alias kgcmalloyaml='kubectl get configmap --all-namespaces -o=yaml'
alias kgsecalloyaml='kubectl get secret --all-namespaces -o=yaml'
alias kgnsalloyaml='kubectl get namespaces --all-namespaces -o=yaml'
alias kgwoyaml='kubectl get --watch -o=yaml'
alias kgpowoyaml='kubectl get pods --watch -o=yaml'
alias kgdepwoyaml='kubectl get deployment --watch -o=yaml'
alias kgsvcwoyaml='kubectl get service --watch -o=yaml'
alias kgingwoyaml='kubectl get ingress --watch -o=yaml'
alias kgcmwoyaml='kubectl get configmap --watch -o=yaml'
alias kgsecwoyaml='kubectl get secret --watch -o=yaml'
alias kgnowoyaml='kubectl get nodes --watch -o=yaml'
alias kgnswoyaml='kubectl get namespaces --watch -o=yaml'
alias kgowideall='kubectl get -o=wide --all-namespaces'
alias kgpoowideall='kubectl get pods -o=wide --all-namespaces'
alias kgdepowideall='kubectl get deployment -o=wide --all-namespaces'
alias kgsvcowideall='kubectl get service -o=wide --all-namespaces'
alias kgingowideall='kubectl get ingress -o=wide --all-namespaces'
alias kgcmowideall='kubectl get configmap -o=wide --all-namespaces'
alias kgsecowideall='kubectl get secret -o=wide --all-namespaces'
alias kgnsowideall='kubectl get namespaces -o=wide --all-namespaces'
alias kgallowide='kubectl get --all-namespaces -o=wide'
alias kgpoallowide='kubectl get pods --all-namespaces -o=wide'
alias kgdepallowide='kubectl get deployment --all-namespaces -o=wide'
alias kgsvcallowide='kubectl get service --all-namespaces -o=wide'
alias kgingallowide='kubectl get ingress --all-namespaces -o=wide'
alias kgcmallowide='kubectl get configmap --all-namespaces -o=wide'
alias kgsecallowide='kubectl get secret --all-namespaces -o=wide'
alias kgnsallowide='kubectl get namespaces --all-namespaces -o=wide'
alias kgowidesl='kubectl get -o=wide --show-labels'
alias kgpoowidesl='kubectl get pods -o=wide --show-labels'
alias kgdepowidesl='kubectl get deployment -o=wide --show-labels'
alias kgslowide='kubectl get --show-labels -o=wide'
alias kgposlowide='kubectl get pods --show-labels -o=wide'
alias kgdepslowide='kubectl get deployment --show-labels -o=wide'
alias kgwowide='kubectl get --watch -o=wide'
alias kgpowowide='kubectl get pods --watch -o=wide'
alias kgdepwowide='kubectl get deployment --watch -o=wide'
alias kgsvcwowide='kubectl get service --watch -o=wide'
alias kgingwowide='kubectl get ingress --watch -o=wide'
alias kgcmwowide='kubectl get configmap --watch -o=wide'
alias kgsecwowide='kubectl get secret --watch -o=wide'
alias kgnowowide='kubectl get nodes --watch -o=wide'
alias kgnswowide='kubectl get namespaces --watch -o=wide'
alias kgojsonall='kubectl get -o=json --all-namespaces'
alias kgpoojsonall='kubectl get pods -o=json --all-namespaces'
alias kgdepojsonall='kubectl get deployment -o=json --all-namespaces'
alias kgsvcojsonall='kubectl get service -o=json --all-namespaces'
alias kgingojsonall='kubectl get ingress -o=json --all-namespaces'
alias kgcmojsonall='kubectl get configmap -o=json --all-namespaces'
alias kgsecojsonall='kubectl get secret -o=json --all-namespaces'
alias kgnsojsonall='kubectl get namespaces -o=json --all-namespaces'
alias kgallojson='kubectl get --all-namespaces -o=json'
alias kgpoallojson='kubectl get pods --all-namespaces -o=json'
alias kgdepallojson='kubectl get deployment --all-namespaces -o=json'
alias kgsvcallojson='kubectl get service --all-namespaces -o=json'
alias kgingallojson='kubectl get ingress --all-namespaces -o=json'
alias kgcmallojson='kubectl get configmap --all-namespaces -o=json'
alias kgsecallojson='kubectl get secret --all-namespaces -o=json'
alias kgnsallojson='kubectl get namespaces --all-namespaces -o=json'
alias kgwojson='kubectl get --watch -o=json'
alias kgpowojson='kubectl get pods --watch -o=json'
alias kgdepwojson='kubectl get deployment --watch -o=json'
alias kgsvcwojson='kubectl get service --watch -o=json'
alias kgingwojson='kubectl get ingress --watch -o=json'
alias kgcmwojson='kubectl get configmap --watch -o=json'
alias kgsecwojson='kubectl get secret --watch -o=json'
alias kgnowojson='kubectl get nodes --watch -o=json'
alias kgnswojson='kubectl get namespaces --watch -o=json'
alias kgallsl='kubectl get --all-namespaces --show-labels'
alias kgpoallsl='kubectl get pods --all-namespaces --show-labels'
alias kgdepallsl='kubectl get deployment --all-namespaces --show-labels'
alias kgslall='kubectl get --show-labels --all-namespaces'
alias kgposlall='kubectl get pods --show-labels --all-namespaces'
alias kgdepslall='kubectl get deployment --show-labels --all-namespaces'
alias kgallw='kubectl get --all-namespaces --watch'
alias kgpoallw='kubectl get pods --all-namespaces --watch'
alias kgdepallw='kubectl get deployment --all-namespaces --watch'
alias kgsvcallw='kubectl get service --all-namespaces --watch'
alias kgingallw='kubectl get ingress --all-namespaces --watch'
alias kgcmallw='kubectl get configmap --all-namespaces --watch'
alias kgsecallw='kubectl get secret --all-namespaces --watch'
alias kgnsallw='kubectl get namespaces --all-namespaces --watch'
alias kgwall='kubectl get --watch --all-namespaces'
alias kgpowall='kubectl get pods --watch --all-namespaces'
alias kgdepwall='kubectl get deployment --watch --all-namespaces'
alias kgsvcwall='kubectl get service --watch --all-namespaces'
alias kgingwall='kubectl get ingress --watch --all-namespaces'
alias kgcmwall='kubectl get configmap --watch --all-namespaces'
alias kgsecwall='kubectl get secret --watch --all-namespaces'
alias kgnswall='kubectl get namespaces --watch --all-namespaces'
alias kgslw='kubectl get --show-labels --watch'
alias kgposlw='kubectl get pods --show-labels --watch'
alias kgdepslw='kubectl get deployment --show-labels --watch'
alias kgwsl='kubectl get --watch --show-labels'
alias kgpowsl='kubectl get pods --watch --show-labels'
alias kgdepwsl='kubectl get deployment --watch --show-labels'
alias kgallwoyaml='kubectl get --all-namespaces --watch -o=yaml'
alias kgpoallwoyaml='kubectl get pods --all-namespaces --watch -o=yaml'
alias kgdepallwoyaml='kubectl get deployment --all-namespaces --watch -o=yaml'
alias kgsvcallwoyaml='kubectl get service --all-namespaces --watch -o=yaml'
alias kgingallwoyaml='kubectl get ingress --all-namespaces --watch -o=yaml'
alias kgcmallwoyaml='kubectl get configmap --all-namespaces --watch -o=yaml'
alias kgsecallwoyaml='kubectl get secret --all-namespaces --watch -o=yaml'
alias kgnsallwoyaml='kubectl get namespaces --all-namespaces --watch -o=yaml'
alias kgwoyamlall='kubectl get --watch -o=yaml --all-namespaces'
alias kgpowoyamlall='kubectl get pods --watch -o=yaml --all-namespaces'
alias kgdepwoyamlall='kubectl get deployment --watch -o=yaml --all-namespaces'
alias kgsvcwoyamlall='kubectl get service --watch -o=yaml --all-namespaces'
alias kgingwoyamlall='kubectl get ingress --watch -o=yaml --all-namespaces'
alias kgcmwoyamlall='kubectl get configmap --watch -o=yaml --all-namespaces'
alias kgsecwoyamlall='kubectl get secret --watch -o=yaml --all-namespaces'
alias kgnswoyamlall='kubectl get namespaces --watch -o=yaml --all-namespaces'
alias kgwalloyaml='kubectl get --watch --all-namespaces -o=yaml'
alias kgpowalloyaml='kubectl get pods --watch --all-namespaces -o=yaml'
alias kgdepwalloyaml='kubectl get deployment --watch --all-namespaces -o=yaml'
alias kgsvcwalloyaml='kubectl get service --watch --all-namespaces -o=yaml'
alias kgingwalloyaml='kubectl get ingress --watch --all-namespaces -o=yaml'
alias kgcmwalloyaml='kubectl get configmap --watch --all-namespaces -o=yaml'
alias kgsecwalloyaml='kubectl get secret --watch --all-namespaces -o=yaml'
alias kgnswalloyaml='kubectl get namespaces --watch --all-namespaces -o=yaml'
alias kgowideallsl='kubectl get -o=wide --all-namespaces --show-labels'
alias kgpoowideallsl='kubectl get pods -o=wide --all-namespaces --show-labels'
alias kgdepowideallsl='kubectl get deployment -o=wide --all-namespaces --show-labels'
alias kgowideslall='kubectl get -o=wide --show-labels --all-namespaces'
alias kgpoowideslall='kubectl get pods -o=wide --show-labels --all-namespaces'
alias kgdepowideslall='kubectl get deployment -o=wide --show-labels --all-namespaces'
alias kgallowidesl='kubectl get --all-namespaces -o=wide --show-labels'
alias kgpoallowidesl='kubectl get pods --all-namespaces -o=wide --show-labels'
alias kgdepallowidesl='kubectl get deployment --all-namespaces -o=wide --show-labels'
alias kgallslowide='kubectl get --all-namespaces --show-labels -o=wide'
alias kgpoallslowide='kubectl get pods --all-namespaces --show-labels -o=wide'
alias kgdepallslowide='kubectl get deployment --all-namespaces --show-labels -o=wide'
alias kgslowideall='kubectl get --show-labels -o=wide --all-namespaces'
alias kgposlowideall='kubectl get pods --show-labels -o=wide --all-namespaces'
alias kgdepslowideall='kubectl get deployment --show-labels -o=wide --all-namespaces'
alias kgslallowide='kubectl get --show-labels --all-namespaces -o=wide'
alias kgposlallowide='kubectl get pods --show-labels --all-namespaces -o=wide'
alias kgdepslallowide='kubectl get deployment --show-labels --all-namespaces -o=wide'
alias kgallwowide='kubectl get --all-namespaces --watch -o=wide'
alias kgpoallwowide='kubectl get pods --all-namespaces --watch -o=wide'
alias kgdepallwowide='kubectl get deployment --all-namespaces --watch -o=wide'
alias kgsvcallwowide='kubectl get service --all-namespaces --watch -o=wide'
alias kgingallwowide='kubectl get ingress --all-namespaces --watch -o=wide'
alias kgcmallwowide='kubectl get configmap --all-namespaces --watch -o=wide'
alias kgsecallwowide='kubectl get secret --all-namespaces --watch -o=wide'
alias kgnsallwowide='kubectl get namespaces --all-namespaces --watch -o=wide'
alias kgwowideall='kubectl get --watch -o=wide --all-namespaces'
alias kgpowowideall='kubectl get pods --watch -o=wide --all-namespaces'
alias kgdepwowideall='kubectl get deployment --watch -o=wide --all-namespaces'
alias kgsvcwowideall='kubectl get service --watch -o=wide --all-namespaces'
alias kgingwowideall='kubectl get ingress --watch -o=wide --all-namespaces'
alias kgcmwowideall='kubectl get configmap --watch -o=wide --all-namespaces'
alias kgsecwowideall='kubectl get secret --watch -o=wide --all-namespaces'
alias kgnswowideall='kubectl get namespaces --watch -o=wide --all-namespaces'
alias kgwallowide='kubectl get --watch --all-namespaces -o=wide'
alias kgpowallowide='kubectl get pods --watch --all-namespaces -o=wide'
alias kgdepwallowide='kubectl get deployment --watch --all-namespaces -o=wide'
alias kgsvcwallowide='kubectl get service --watch --all-namespaces -o=wide'
alias kgingwallowide='kubectl get ingress --watch --all-namespaces -o=wide'
alias kgcmwallowide='kubectl get configmap --watch --all-namespaces -o=wide'
alias kgsecwallowide='kubectl get secret --watch --all-namespaces -o=wide'
alias kgnswallowide='kubectl get namespaces --watch --all-namespaces -o=wide'
alias kgslwowide='kubectl get --show-labels --watch -o=wide'
alias kgposlwowide='kubectl get pods --show-labels --watch -o=wide'
alias kgdepslwowide='kubectl get deployment --show-labels --watch -o=wide'
alias kgwowidesl='kubectl get --watch -o=wide --show-labels'
alias kgpowowidesl='kubectl get pods --watch -o=wide --show-labels'
alias kgdepwowidesl='kubectl get deployment --watch -o=wide --show-labels'
alias kgwslowide='kubectl get --watch --show-labels -o=wide'
alias kgpowslowide='kubectl get pods --watch --show-labels -o=wide'
alias kgdepwslowide='kubectl get deployment --watch --show-labels -o=wide'
alias kgallwojson='kubectl get --all-namespaces --watch -o=json'
alias kgpoallwojson='kubectl get pods --all-namespaces --watch -o=json'
alias kgdepallwojson='kubectl get deployment --all-namespaces --watch -o=json'
alias kgsvcallwojson='kubectl get service --all-namespaces --watch -o=json'
alias kgingallwojson='kubectl get ingress --all-namespaces --watch -o=json'
alias kgcmallwojson='kubectl get configmap --all-namespaces --watch -o=json'
alias kgsecallwojson='kubectl get secret --all-namespaces --watch -o=json'
alias kgnsallwojson='kubectl get namespaces --all-namespaces --watch -o=json'
alias kgwojsonall='kubectl get --watch -o=json --all-namespaces'
alias kgpowojsonall='kubectl get pods --watch -o=json --all-namespaces'
alias kgdepwojsonall='kubectl get deployment --watch -o=json --all-namespaces'
alias kgsvcwojsonall='kubectl get service --watch -o=json --all-namespaces'
alias kgingwojsonall='kubectl get ingress --watch -o=json --all-namespaces'
alias kgcmwojsonall='kubectl get configmap --watch -o=json --all-namespaces'
alias kgsecwojsonall='kubectl get secret --watch -o=json --all-namespaces'
alias kgnswojsonall='kubectl get namespaces --watch -o=json --all-namespaces'
alias kgwallojson='kubectl get --watch --all-namespaces -o=json'
alias kgpowallojson='kubectl get pods --watch --all-namespaces -o=json'
alias kgdepwallojson='kubectl get deployment --watch --all-namespaces -o=json'
alias kgsvcwallojson='kubectl get service --watch --all-namespaces -o=json'
alias kgingwallojson='kubectl get ingress --watch --all-namespaces -o=json'
alias kgcmwallojson='kubectl get configmap --watch --all-namespaces -o=json'
alias kgsecwallojson='kubectl get secret --watch --all-namespaces -o=json'
alias kgnswallojson='kubectl get namespaces --watch --all-namespaces -o=json'
alias kgallslw='kubectl get --all-namespaces --show-labels --watch'
alias kgpoallslw='kubectl get pods --all-namespaces --show-labels --watch'
alias kgdepallslw='kubectl get deployment --all-namespaces --show-labels --watch'
alias kgallwsl='kubectl get --all-namespaces --watch --show-labels'
alias kgpoallwsl='kubectl get pods --all-namespaces --watch --show-labels'
alias kgdepallwsl='kubectl get deployment --all-namespaces --watch --show-labels'
alias kgslallw='kubectl get --show-labels --all-namespaces --watch'
alias kgposlallw='kubectl get pods --show-labels --all-namespaces --watch'
alias kgdepslallw='kubectl get deployment --show-labels --all-namespaces --watch'
alias kgslwall='kubectl get --show-labels --watch --all-namespaces'
alias kgposlwall='kubectl get pods --show-labels --watch --all-namespaces'
alias kgdepslwall='kubectl get deployment --show-labels --watch --all-namespaces'
alias kgwallsl='kubectl get --watch --all-namespaces --show-labels'
alias kgpowallsl='kubectl get pods --watch --all-namespaces --show-labels'
alias kgdepwallsl='kubectl get deployment --watch --all-namespaces --show-labels'
alias kgwslall='kubectl get --watch --show-labels --all-namespaces'
alias kgpowslall='kubectl get pods --watch --show-labels --all-namespaces'
alias kgdepwslall='kubectl get deployment --watch --show-labels --all-namespaces'
alias kgallslwowide='kubectl get --all-namespaces --show-labels --watch -o=wide'
alias kgpoallslwowide='kubectl get pods --all-namespaces --show-labels --watch -o=wide'
alias kgdepallslwowide='kubectl get deployment --all-namespaces --show-labels --watch -o=wide'
alias kgallwowidesl='kubectl get --all-namespaces --watch -o=wide --show-labels'
alias kgpoallwowidesl='kubectl get pods --all-namespaces --watch -o=wide --show-labels'
alias kgdepallwowidesl='kubectl get deployment --all-namespaces --watch -o=wide --show-labels'
alias kgallwslowide='kubectl get --all-namespaces --watch --show-labels -o=wide'
alias kgpoallwslowide='kubectl get pods --all-namespaces --watch --show-labels -o=wide'
alias kgdepallwslowide='kubectl get deployment --all-namespaces --watch --show-labels -o=wide'
alias kgslallwowide='kubectl get --show-labels --all-namespaces --watch -o=wide'
alias kgposlallwowide='kubectl get pods --show-labels --all-namespaces --watch -o=wide'
alias kgdepslallwowide='kubectl get deployment --show-labels --all-namespaces --watch -o=wide'
alias kgslwowideall='kubectl get --show-labels --watch -o=wide --all-namespaces'
alias kgposlwowideall='kubectl get pods --show-labels --watch -o=wide --all-namespaces'
alias kgdepslwowideall='kubectl get deployment --show-labels --watch -o=wide --all-namespaces'
alias kgslwallowide='kubectl get --show-labels --watch --all-namespaces -o=wide'
alias kgposlwallowide='kubectl get pods --show-labels --watch --all-namespaces -o=wide'
alias kgdepslwallowide='kubectl get deployment --show-labels --watch --all-namespaces -o=wide'
alias kgwowideallsl='kubectl get --watch -o=wide --all-namespaces --show-labels'
alias kgpowowideallsl='kubectl get pods --watch -o=wide --all-namespaces --show-labels'
alias kgdepwowideallsl='kubectl get deployment --watch -o=wide --all-namespaces --show-labels'
alias kgwowideslall='kubectl get --watch -o=wide --show-labels --all-namespaces'
alias kgpowowideslall='kubectl get pods --watch -o=wide --show-labels --all-namespaces'
alias kgdepwowideslall='kubectl get deployment --watch -o=wide --show-labels --all-namespaces'
alias kgwallowidesl='kubectl get --watch --all-namespaces -o=wide --show-labels'
alias kgpowallowidesl='kubectl get pods --watch --all-namespaces -o=wide --show-labels'
alias kgdepwallowidesl='kubectl get deployment --watch --all-namespaces -o=wide --show-labels'
alias kgwallslowide='kubectl get --watch --all-namespaces --show-labels -o=wide'
alias kgpowallslowide='kubectl get pods --watch --all-namespaces --show-labels -o=wide'
alias kgdepwallslowide='kubectl get deployment --watch --all-namespaces --show-labels -o=wide'
alias kgwslowideall='kubectl get --watch --show-labels -o=wide --all-namespaces'
alias kgpowslowideall='kubectl get pods --watch --show-labels -o=wide --all-namespaces'
alias kgdepwslowideall='kubectl get deployment --watch --show-labels -o=wide --all-namespaces'
alias kgwslallowide='kubectl get --watch --show-labels --all-namespaces -o=wide'
alias kgpowslallowide='kubectl get pods --watch --show-labels --all-namespaces -o=wide'
alias kgdepwslallowide='kubectl get deployment --watch --show-labels --all-namespaces -o=wide'
alias kgf='kubectl get --recursive -f'
alias kdf='kubectl describe --recursive -f'
alias krmf='kubectl delete --recursive -f'
alias kgoyamlf='kubectl get -o=yaml --recursive -f'
alias kgowidef='kubectl get -o=wide --recursive -f'
alias kgojsonf='kubectl get -o=json --recursive -f'
alias kgslf='kubectl get --show-labels --recursive -f'
alias kgwf='kubectl get --watch --recursive -f'
alias kgwoyamlf='kubectl get --watch -o=yaml --recursive -f'
alias kgowideslf='kubectl get -o=wide --show-labels --recursive -f'
alias kgslowidef='kubectl get --show-labels -o=wide --recursive -f'
alias kgwowidef='kubectl get --watch -o=wide --recursive -f'
alias kgwojsonf='kubectl get --watch -o=json --recursive -f'
alias kgslwf='kubectl get --show-labels --watch --recursive -f'
alias kgwslf='kubectl get --watch --show-labels --recursive -f'
alias kgslwowidef='kubectl get --show-labels --watch -o=wide --recursive -f'
alias kgwowideslf='kubectl get --watch -o=wide --show-labels --recursive -f'
alias kgwslowidef='kubectl get --watch --show-labels -o=wide --recursive -f'
alias kgl='kubectl get -l'
alias kdl='kubectl describe -l'
alias krml='kubectl delete -l'
alias kgpol='kubectl get pods -l'
alias kdpol='kubectl describe pods -l'
alias krmpol='kubectl delete pods -l'
alias kgdepl='kubectl get deployment -l'
alias kddepl='kubectl describe deployment -l'
alias krmdepl='kubectl delete deployment -l'
alias kgsvcl='kubectl get service -l'
alias kdsvcl='kubectl describe service -l'
alias krmsvcl='kubectl delete service -l'
alias kgingl='kubectl get ingress -l'
alias kdingl='kubectl describe ingress -l'
alias krmingl='kubectl delete ingress -l'
alias kgcml='kubectl get configmap -l'
alias kdcml='kubectl describe configmap -l'
alias krmcml='kubectl delete configmap -l'
alias kgsecl='kubectl get secret -l'
alias kdsecl='kubectl describe secret -l'
alias krmsecl='kubectl delete secret -l'
alias kgnol='kubectl get nodes -l'
alias kdnol='kubectl describe nodes -l'
alias kgnsl='kubectl get namespaces -l'
alias kdnsl='kubectl describe namespaces -l'
alias krmnsl='kubectl delete namespaces -l'
alias kgoyamll='kubectl get -o=yaml -l'
alias kgpooyamll='kubectl get pods -o=yaml -l'
alias kgdepoyamll='kubectl get deployment -o=yaml -l'
alias kgsvcoyamll='kubectl get service -o=yaml -l'
alias kgingoyamll='kubectl get ingress -o=yaml -l'
alias kgcmoyamll='kubectl get configmap -o=yaml -l'
alias kgsecoyamll='kubectl get secret -o=yaml -l'
alias kgnooyamll='kubectl get nodes -o=yaml -l'
alias kgnsoyamll='kubectl get namespaces -o=yaml -l'
alias kgowidel='kubectl get -o=wide -l'
alias kgpoowidel='kubectl get pods -o=wide -l'
alias kgdepowidel='kubectl get deployment -o=wide -l'
alias kgsvcowidel='kubectl get service -o=wide -l'
alias kgingowidel='kubectl get ingress -o=wide -l'
alias kgcmowidel='kubectl get configmap -o=wide -l'
alias kgsecowidel='kubectl get secret -o=wide -l'
alias kgnoowidel='kubectl get nodes -o=wide -l'
alias kgnsowidel='kubectl get namespaces -o=wide -l'
alias kgojsonl='kubectl get -o=json -l'
alias kgpoojsonl='kubectl get pods -o=json -l'
alias kgdepojsonl='kubectl get deployment -o=json -l'
alias kgsvcojsonl='kubectl get service -o=json -l'
alias kgingojsonl='kubectl get ingress -o=json -l'
alias kgcmojsonl='kubectl get configmap -o=json -l'
alias kgsecojsonl='kubectl get secret -o=json -l'
alias kgnoojsonl='kubectl get nodes -o=json -l'
alias kgnsojsonl='kubectl get namespaces -o=json -l'
alias kgsll='kubectl get --show-labels -l'
alias kgposll='kubectl get pods --show-labels -l'
alias kgdepsll='kubectl get deployment --show-labels -l'
alias kgwl='kubectl get --watch -l'
alias kgpowl='kubectl get pods --watch -l'
alias kgdepwl='kubectl get deployment --watch -l'
alias kgsvcwl='kubectl get service --watch -l'
alias kgingwl='kubectl get ingress --watch -l'
alias kgcmwl='kubectl get configmap --watch -l'
alias kgsecwl='kubectl get secret --watch -l'
alias kgnowl='kubectl get nodes --watch -l'
alias kgnswl='kubectl get namespaces --watch -l'
alias kgwoyamll='kubectl get --watch -o=yaml -l'
alias kgpowoyamll='kubectl get pods --watch -o=yaml -l'
alias kgdepwoyamll='kubectl get deployment --watch -o=yaml -l'
alias kgsvcwoyamll='kubectl get service --watch -o=yaml -l'
alias kgingwoyamll='kubectl get ingress --watch -o=yaml -l'
alias kgcmwoyamll='kubectl get configmap --watch -o=yaml -l'
alias kgsecwoyamll='kubectl get secret --watch -o=yaml -l'
alias kgnowoyamll='kubectl get nodes --watch -o=yaml -l'
alias kgnswoyamll='kubectl get namespaces --watch -o=yaml -l'
alias kgowidesll='kubectl get -o=wide --show-labels -l'
alias kgpoowidesll='kubectl get pods -o=wide --show-labels -l'
alias kgdepowidesll='kubectl get deployment -o=wide --show-labels -l'
alias kgslowidel='kubectl get --show-labels -o=wide -l'
alias kgposlowidel='kubectl get pods --show-labels -o=wide -l'
alias kgdepslowidel='kubectl get deployment --show-labels -o=wide -l'
alias kgwowidel='kubectl get --watch -o=wide -l'
alias kgpowowidel='kubectl get pods --watch -o=wide -l'
alias kgdepwowidel='kubectl get deployment --watch -o=wide -l'
alias kgsvcwowidel='kubectl get service --watch -o=wide -l'
alias kgingwowidel='kubectl get ingress --watch -o=wide -l'
alias kgcmwowidel='kubectl get configmap --watch -o=wide -l'
alias kgsecwowidel='kubectl get secret --watch -o=wide -l'
alias kgnowowidel='kubectl get nodes --watch -o=wide -l'
alias kgnswowidel='kubectl get namespaces --watch -o=wide -l'
alias kgwojsonl='kubectl get --watch -o=json -l'
alias kgpowojsonl='kubectl get pods --watch -o=json -l'
alias kgdepwojsonl='kubectl get deployment --watch -o=json -l'
alias kgsvcwojsonl='kubectl get service --watch -o=json -l'
alias kgingwojsonl='kubectl get ingress --watch -o=json -l'
alias kgcmwojsonl='kubectl get configmap --watch -o=json -l'
alias kgsecwojsonl='kubectl get secret --watch -o=json -l'
alias kgnowojsonl='kubectl get nodes --watch -o=json -l'
alias kgnswojsonl='kubectl get namespaces --watch -o=json -l'
alias kgslwl='kubectl get --show-labels --watch -l'
alias kgposlwl='kubectl get pods --show-labels --watch -l'
alias kgdepslwl='kubectl get deployment --show-labels --watch -l'
alias kgwsll='kubectl get --watch --show-labels -l'
alias kgpowsll='kubectl get pods --watch --show-labels -l'
alias kgdepwsll='kubectl get deployment --watch --show-labels -l'
alias kgslwowidel='kubectl get --show-labels --watch -o=wide -l'
alias kgposlwowidel='kubectl get pods --show-labels --watch -o=wide -l'
alias kgdepslwowidel='kubectl get deployment --show-labels --watch -o=wide -l'
alias kgwowidesll='kubectl get --watch -o=wide --show-labels -l'
alias kgpowowidesll='kubectl get pods --watch -o=wide --show-labels -l'
alias kgdepwowidesll='kubectl get deployment --watch -o=wide --show-labels -l'
alias kgwslowidel='kubectl get --watch --show-labels -o=wide -l'
alias kgpowslowidel='kubectl get pods --watch --show-labels -o=wide -l'
alias kgdepwslowidel='kubectl get deployment --watch --show-labels -o=wide -l'
alias kexns='kubectl exec -i -t --namespace'
alias klons='kubectl logs -f --namespace'
alias kpfns='kubectl port-forward --namespace'
alias kgns='kubectl get --namespace'
alias kdns='kubectl describe --namespace'
alias krmns='kubectl delete --namespace'
alias kgpons='kubectl get pods --namespace'
alias kdpons='kubectl describe pods --namespace'
alias krmpons='kubectl delete pods --namespace'
alias kgdepns='kubectl get deployment --namespace'
alias kddepns='kubectl describe deployment --namespace'
alias krmdepns='kubectl delete deployment --namespace'
alias kgsvcns='kubectl get service --namespace'
alias kdsvcns='kubectl describe service --namespace'
alias krmsvcns='kubectl delete service --namespace'
alias kgingns='kubectl get ingress --namespace'
alias kdingns='kubectl describe ingress --namespace'
alias krmingns='kubectl delete ingress --namespace'
alias kgcmns='kubectl get configmap --namespace'
alias kdcmns='kubectl describe configmap --namespace'
alias krmcmns='kubectl delete configmap --namespace'
alias kgsecns='kubectl get secret --namespace'
alias kdsecns='kubectl describe secret --namespace'
alias krmsecns='kubectl delete secret --namespace'
alias kgoyamlns='kubectl get -o=yaml --namespace'
alias kgpooyamlns='kubectl get pods -o=yaml --namespace'
alias kgdepoyamlns='kubectl get deployment -o=yaml --namespace'
alias kgsvcoyamlns='kubectl get service -o=yaml --namespace'
alias kgingoyamlns='kubectl get ingress -o=yaml --namespace'
alias kgcmoyamlns='kubectl get configmap -o=yaml --namespace'
alias kgsecoyamlns='kubectl get secret -o=yaml --namespace'
alias kgowidens='kubectl get -o=wide --namespace'
alias kgpoowidens='kubectl get pods -o=wide --namespace'
alias kgdepowidens='kubectl get deployment -o=wide --namespace'
alias kgsvcowidens='kubectl get service -o=wide --namespace'
alias kgingowidens='kubectl get ingress -o=wide --namespace'
alias kgcmowidens='kubectl get configmap -o=wide --namespace'
alias kgsecowidens='kubectl get secret -o=wide --namespace'
alias kgojsonns='kubectl get -o=json --namespace'
alias kgpoojsonns='kubectl get pods -o=json --namespace'
alias kgdepojsonns='kubectl get deployment -o=json --namespace'
alias kgsvcojsonns='kubectl get service -o=json --namespace'
alias kgingojsonns='kubectl get ingress -o=json --namespace'
alias kgcmojsonns='kubectl get configmap -o=json --namespace'
alias kgsecojsonns='kubectl get secret -o=json --namespace'
alias kgslns='kubectl get --show-labels --namespace'
alias kgposlns='kubectl get pods --show-labels --namespace'
alias kgdepslns='kubectl get deployment --show-labels --namespace'
alias kgwns='kubectl get --watch --namespace'
alias kgpowns='kubectl get pods --watch --namespace'
alias kgdepwns='kubectl get deployment --watch --namespace'
alias kgsvcwns='kubectl get service --watch --namespace'
alias kgingwns='kubectl get ingress --watch --namespace'
alias kgcmwns='kubectl get configmap --watch --namespace'
alias kgsecwns='kubectl get secret --watch --namespace'
alias kgwoyamlns='kubectl get --watch -o=yaml --namespace'
alias kgpowoyamlns='kubectl get pods --watch -o=yaml --namespace'
alias kgdepwoyamlns='kubectl get deployment --watch -o=yaml --namespace'
alias kgsvcwoyamlns='kubectl get service --watch -o=yaml --namespace'
alias kgingwoyamlns='kubectl get ingress --watch -o=yaml --namespace'
alias kgcmwoyamlns='kubectl get configmap --watch -o=yaml --namespace'
alias kgsecwoyamlns='kubectl get secret --watch -o=yaml --namespace'
alias kgowideslns='kubectl get -o=wide --show-labels --namespace'
alias kgpoowideslns='kubectl get pods -o=wide --show-labels --namespace'
alias kgdepowideslns='kubectl get deployment -o=wide --show-labels --namespace'
alias kgslowidens='kubectl get --show-labels -o=wide --namespace'
alias kgposlowidens='kubectl get pods --show-labels -o=wide --namespace'
alias kgdepslowidens='kubectl get deployment --show-labels -o=wide --namespace'
alias kgwowidens='kubectl get --watch -o=wide --namespace'
alias kgpowowidens='kubectl get pods --watch -o=wide --namespace'
alias kgdepwowidens='kubectl get deployment --watch -o=wide --namespace'
alias kgsvcwowidens='kubectl get service --watch -o=wide --namespace'
alias kgingwowidens='kubectl get ingress --watch -o=wide --namespace'
alias kgcmwowidens='kubectl get configmap --watch -o=wide --namespace'
alias kgsecwowidens='kubectl get secret --watch -o=wide --namespace'
alias kgwojsonns='kubectl get --watch -o=json --namespace'
alias kgpowojsonns='kubectl get pods --watch -o=json --namespace'
alias kgdepwojsonns='kubectl get deployment --watch -o=json --namespace'
alias kgsvcwojsonns='kubectl get service --watch -o=json --namespace'
alias kgingwojsonns='kubectl get ingress --watch -o=json --namespace'
alias kgcmwojsonns='kubectl get configmap --watch -o=json --namespace'
alias kgsecwojsonns='kubectl get secret --watch -o=json --namespace'
alias kgslwns='kubectl get --show-labels --watch --namespace'
alias kgposlwns='kubectl get pods --show-labels --watch --namespace'
alias kgdepslwns='kubectl get deployment --show-labels --watch --namespace'
alias kgwslns='kubectl get --watch --show-labels --namespace'
alias kgpowslns='kubectl get pods --watch --show-labels --namespace'
alias kgdepwslns='kubectl get deployment --watch --show-labels --namespace'
alias kgslwowidens='kubectl get --show-labels --watch -o=wide --namespace'
alias kgposlwowidens='kubectl get pods --show-labels --watch -o=wide --namespace'
alias kgdepslwowidens='kubectl get deployment --show-labels --watch -o=wide --namespace'
alias kgwowideslns='kubectl get --watch -o=wide --show-labels --namespace'
alias kgpowowideslns='kubectl get pods --watch -o=wide --show-labels --namespace'
alias kgdepwowideslns='kubectl get deployment --watch -o=wide --show-labels --namespace'
alias kgwslowidens='kubectl get --watch --show-labels -o=wide --namespace'
alias kgpowslowidens='kubectl get pods --watch --show-labels -o=wide --namespace'
alias kgdepwslowidens='kubectl get deployment --watch --show-labels -o=wide --namespace'
