#!/usr/bin/env bash

export PATH="$PWD/setup:$PATH"

# Setup Homebrew
log info "Installing Homebrew packages and casks..."
(
	cd ./backup

	NONINTERACTIVE=1 brew bundle install | while read -r line; do
		log info "${line}"
	done
)

log info "Homebrew setup complete (if there were errors, fix them, and re-run the script)"