#!/usr/bin/env bash

export PATH="$PWD/setup:$PATH"

log info "Installing node-related things..."

log info "Starting with 'n'..."
curl -L https://git.io/n-install | N_PREFIX=~/.n bash -s -- -y

log info "Installing Node LTS..."
n lts

log info "Installing Node latest..."
n latest

log info "Now instlaling global packages under latest node..."
npm install -g backup-global
backup-global install --input ./backup/npm.global.backup.txt
