#!/usr/bin/env bash

log info "Installing VSCode extensions..."

( 
	(
		grep -v '^#' |
			xargs -L1 code --install-extension
	) <./backup/vscode-extensions-backup.txt
) || true # continue even if we already have it

curl "https://raw.githubusercontent.com/github/linguist/master/lib/linguist/languages.yml" |
	yq '.[].extensions - [null] | unique | .[]' |
	xargs -L 1 -I {} duti -s com.microsoft.VSCode {} all
