#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
  bootsrap_before = "myspacevim#before"
  bootstrap_after = "myspacevim#after"
  # autocomplete_method = "coc"
  buffer_index_type = 4
  checkinstall = true
  enable_googlesuggest = 1
  enable_tabline_ft_icon = true
  filetree_direction = "left"
  github_username = "macintacos"

  # THEMING {{{
  colorscheme = "dracula"
  colorscheme_bg = "dark"
  enable_guicolors = true
  enable_statusline_mode = true
  enable_tabline_filetype_icon = true
  enable_os_fileformat_icon = true
  enable_ale = true

  statusline_left_sections = [
    'winnr',
    'filename',
    'major mode',
    'minor mode lighters',
    'version control info'
  ]

  statusline_right_sections = [
    'cursorpos',
    'percentage'
  ]

  # Custom pallete for the statusline because this thing is annoying;
  # may want to change colors some other time
  custom_color_palette = [
    ['#282C34', '#bd93f9', 114, 235],
    ['#ABB2BF', '#45475b', 236, 144],
    ['#ABB2BF', '#282a36', 238, 144],
    ['#282a36', 59],
    ['#282c34', '#FF79C6', 235, 36],
    ['#282c34', '#ff5655', 235, 208],
    ['#282c34', '#af5f5f', 235, 131],
    ['#282828', '#689d6a', 235, 72],
    ['#282828', '#8f3f71', 235, 132],
  ]

  # }}}

# Layerz
[[layers]]
name = "autocomplete"
auto-completion-return-key-behavior = "smart"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = "shell"
default_position = "bottom"
default_height = 30

[[layers]]
name = "format"

[[layers]]
name = "git"
git-plugin = "fugitive"

[[layers]]
name = "lang#dockerfile"

[[layers]]
name = "lang#python"
enable_typeinfo = true
format_on_save = 1

[[layers]]
name = "denite"

[[layers]]
name = "debug"

[[layers]]
name = "lang#c"

[[layers]]
name = "lang#go"

[[layers]]
name = "lang#html"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#java"

[[layers]]
name = "lang#json"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#rust"
recommended-style = 1
format-autosave = 1

[[layers]]
name = "lang#sh"

[[layers]]
name = "lang#swift"

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#typescript"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lsp"

[[layers]]
name = "sudo"

[[layers]]
name = "tools"

[[layers]]
name = "VersionControl"

[[layers]]
name = "gtags"

[[layers]]
name = "ctrlspace"

# CUSTOM PLUGINS {{{
[[custom_plugins]]
name = "dracula/vim"
merged = 0
[[custom_plugins]]
name = "machakann/vim-highlightedyank"
merged = 0
[[custom_plugins]]
name = "reedes/vim-lexical"
merged = 0
[[custom_plugins]]
name = "tpope/vim-commentary"
merged = 0
[[custom_plugins]]
name = "tpope/vim-surround"
merged = 0
[[custom_plugins]]
name = "vimwiki/vimwiki"
merged = 0
[[custom_plugins]]
name = "itchyny/vim-cursorword"
merged = 0
[[custom_plugins]]
name = "ryanoasis/vim-devicons"
merged = 0
[[custom_plugins]]
name = "sheerun/vim-polyglot"
merged = 0
# CUSTOM PLUGINS END }}}
