#!/usr/bin/env bash

export PATH="$PWD/setup:$PATH"

# Most of this comes from https://github.com/mathiasbynens/dotfiles/blob/main/.macos

# ---------------------------------------------------------------------------- #
#                             macOS System Settings                            #
# ---------------------------------------------------------------------------- #

log info "This script will change a bunch of macOS settings to sensible defaults."
log info "We're going to quit System Preferences..."
# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'
log ok "Done."

# Ask for the administrator password upfront
log info "We need your password in order to setup things properly."
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do
    sudo -n true
    sleep 60
    kill -0 "$$" || exit
done 2>/dev/null &
log ok "Time to set everything up!"

# ------------------------------- General UI/UX ------------------------------ #

log info "Changing general UI/UX things..."

log info "Expand save panel by default"
(
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
    defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
) && log ok "Done"

log info "Save to disk (not to iCloud) by default"
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false && log ok "Done"

log info "Disable the 'Are you sure you want to open this application?' dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false && log ok "Done"

log info "Disable automatic termination of inactive apps"
defaults write NSGlobalDomain NSDisableAutomaticTermination -bool true && log ok "Done"

log info "Reveal IP address, hostname, OS version, etc. when clicking the clock in the login window"
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName && log ok "Done"

# ----------------------------- Input Management ----------------------------- #

log info "Changing input things..."

log info "Trackpad: enable tap to click for this user and for the login screen"
(
    defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
    defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
    defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
) && log ok "Done"

log info "Keyboard: allow holding keys to repeat characters indefinitely"
defaults write -g ApplePressAndHoldEnabled -bool false && log ok "Done"

# ------------------------------- Screen Stuff ------------------------------- #

log info "Changing screen stuff..."

log info "Require password immediately after sleep or screen saver begins"
(
    defaults write com.apple.screensaver askForPassword -int 1
    defaults write com.apple.screensaver askForPasswordDelay -int 0
) && log ok "Done"

log info "Enable subpixel font rendering on non-Apple LCDs (Reference: https://github.com/kevinSuttle/macOS-Defaults/issues/17#issuecomment-266633501)"
defaults write NSGlobalDomain AppleFontSmoothing -int 1 && log ok "Done"

# ---------------------------------- Finder ---------------------------------- #

log info "Updating the Finder..."

log info "Show icons for hard drives, servers, and removable media on the desktop"
(
    defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
    defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
    defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
) && log ok "Done"

log info "Finder: show hidden files by default"
log info "Finder: show all filename extensions"
log info "Finder: show status bar"
log info "Finder: show path bar"
log info "Display full POSIX path as Finder window title"
log info "Keep folders on top when sorting by name"
log info "When performing a search, search the current folder by default"
log info "Disable the warning when changing a file extension"
log info "Enable spring loading for directories"
log info "Remove the spring loading delay for directories"
log info "Avoid creating .DS_Store files on network or USB volumes"
log info "Automatically open a new Finder window when a volume is mounted"
(
    defaults write com.apple.finder AppleShowAllFiles -bool true
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true
    defaults write com.apple.finder ShowStatusBar -bool true
    defaults write com.apple.finder ShowPathbar -bool true
    defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
    defaults write com.apple.finder _FXSortFoldersFirst -bool true
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
    defaults write NSGlobalDomain com.apple.springing.enabled -bool true
    defaults write NSGlobalDomain com.apple.springing.delay -float 0
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
    defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
    defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
    defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true
) && log ok "Done"

log info "Show item info near icons on the desktop and in other icon views"
(
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:showItemInfo true" ~/Library/Preferences/com.apple.finder.plist
) && log ok "Done"

log info "Show item info to the right of the icons on the desktop"
/usr/libexec/PlistBuddy -c "Set DesktopViewSettings:IconViewSettings:labelOnBottom false" ~/Library/Preferences/com.apple.finder.plist && log ok "Done"

log info "Enable snap-to-grid for icons on the desktop and in other icon views"
(
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
) && log ok "Done"

log info "Use column view in all Finder windows by default"
log info "Four-letter codes for the other view modes: 'icnv, 'clmv', 'glyv', 'Nlsv'"
defaults write com.apple.finder FXPreferredViewStyle -string "clmv" && log ok "Done"

log info "Disable the warning before emptying the Trash"
defaults write com.apple.finder WarnOnEmptyTrash -bool false && log ok "Done"

log info "Show the ~/Library folder"
chflags nohidden ~/Library && xattr -d com.apple.FinderInfo ~/Library && log ok "Done"

log info "Show the /Volumes folder"
sudo chflags nohidden /Volumes && log ok "Done"

# ---------------------------------- Safari ---------------------------------- #

log info "Updating Safari..."

log info "Enable the Develop menu and the Web Inspector in Safari"
(
    defaults write com.apple.Safari IncludeDevelopMenu -bool true
    defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
    defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true
) && log ok "Done"

log info "Add a context menu item for showing the Web Inspector in web views"
defaults write NSGlobalDomain WebKitDeveloperExtras -bool true && log ok "Done"

log info "Enable 'Do Not Track'"
defaults write com.apple.Safari SendDoNotTrackHTTPHeader -bool true && log ok "Done"

log info "Make Safari’s search banners default to Contains instead of Starts With"
defaults write com.apple.Safari FindOnPageMatchesWordStartsOnly -bool false && log ok "Done"

log info "Show the full URL in the address bar (note: this still hides the scheme)"
defaults write com.apple.Safari ShowFullURLInSmartSearchField -bool true && log ok "Done"

# ---------------------------------- Cleanup --------------------------------- #

log info "Cleaning up..."

for app in \
    "Finder" \
    "Safari"; do
    killall "${app}" &>/dev/null
done

log ok "Setup complete."
log info "Note that some of these changes require a logout/restart to take effect. You should probably do it just to be safe."
