name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - name: Setup just
      uses: extractions/setup-just@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup repository
      uses: actions/checkout@v2
    - name: Testing installation of all dependencies
      run: just install-ci
